### ISSUE TITLE
Aumentar a margem do placeholder

### ISSUE THREAD

**Issue by joaovitormoitinho** [JoseOda/TrabalhoGCS#12]
o placeholder está muito colado na barra de pesquisa, deixaria a aplicação mais elegante se aumentasse essa margin.

![image](https://user-images.githubusercontent.com/83321595/175791805-8e435cb8-eab9-40c0-81df-975b2bfdac03.png)

**Comment by GabrielCGon** [comment]
Beleza, vou iniciar as alterações.

**Comment by hugor1256** [comment]
Muito bem visto, desse jeito ficara muito melhor

**Comment by JoseOda** [comment]
Realmente, acredito que ficaria mais interessante o placeholder mais a direita!

**Comment by hugor1256** [comment]
Já revisei, aprovei, bom trabalho
