### ISSUE TITLE
Adicionar o icon de pesquisa na barra de pesquisa

### ISSUE THREAD

**Issue by JoseOda** [JoseOda/TrabalhoGCS#14]
Seria interessante adicionar um icon de lupa dentro da barra de pesquisa, a fim de melhorar a experiência de usuário

**Comment by joaovitormoitinho** [comment]
concordo, pois assim a barra de pesquisa ficaria mais intuitiva para o usuário

**Comment by joaovitormoitinho** [comment]
@GabrielCGon poderia fazer essa parte ?

**Comment by GabrielCGon** [comment]
Posso, vou implementar.

**Comment by hugor1256** [comment]
Já revisei, aprovei, bom trabalho
