### ISSUE TITLE
Implementação da localização do usuário

### ISSUE THREAD

**Issue by enzookita** [JoseOda/TrabalhoGCS#15]
Ao buscar o usuário, seria interessante adicionar a localização do usuário, verificando a API do GitHub.

**Comment by JoseOda** [comment]
Acredito que realmente seria interessante, só precisamos verificar se na API é possível fazer algo assim

**Comment by hugor1256** [comment]
Verifiquei aqui, é possível sim, já vou começar a fazer essa implementação

**Comment by JoseOda** [comment]
![Captura de tela 2022-06-26 212731](https://user-images.githubusercontent.com/95934487/175840216-bfee5da7-5f60-40a6-85f0-51cc071751b2.jpg)

Realmente @hugor1256 verifiquei aqui na documentação e é possível sim

**Comment by hugor1256** [comment]
Beleza José já vou começar a fazer a implementação!

**Comment by joaovitormoitinho** [comment]
funcionalidade implementada
