### ISSUE TITLE
Implementação para redirecionar a página ao repositório do usuário

### ISSUE THREAD

**Issue by enzookita** [JoseOda/TrabalhoGCS#17]
Acabei encontrado mais uma possível melhoria no programa. O programa mostra os repositórios do usuário, seria interessante deixar os repositórios com com URLs dos repositórios.

**Comment by joaovitormoitinho** [comment]
achei confuso sua colocação, poderia explicar melhor ?

**Comment by JoseOda** [comment]
Acredito que seria bem interessante mesmo, além de ser bem útil é uma melhoria fácil de ser implementada!

**Comment by enzookita** [comment]
![image](https://user-images.githubusercontent.com/68976226/175840479-3cc7416e-f41c-43fe-978e-828d0164cd5e.png)

Segundo a imagem acima, o nosso programa mostra o repositório do usuário, porém não tem interação ao clicar nesse mesmo repositório, seria interessante poder acessar o repositório do usuário.

**Comment by JoseOda** [comment]
Acredito que seria bem fácil a implementação dessa melhoria , já que é so mudarmos na main.js a label para uma tag ancora para poder fazer esse link

**Comment by JoseOda** [comment]
Resolvido esta isssue!
