### ISSUE TITLE
Implementação do modo dark 

### ISSUE THREAD

**Issue by halls2001** [JoseOda/TrabalhoGCS#18]
Acredito que para deixarmos a aplicação mais confortável visualmente devemos implementar um modo dark. Dessa forma, o modo escuro ajudará os dispositivos a economizar bateria e reduzir a tensão nos olhos.

**Comment by enzookita** [comment]
Realmente é uma ótima ideia, existem usuários que preferem utilizar o modo de tela escura. Vou começar a implementação agora mesmo.

**Comment by hugor1256** [comment]
Muito boa ideia, fora que a maioria dos usuários prefere o modo escuro

**Comment by enzookita** [comment]
Foi feita a implementação, revisada e aprovada para a Main
