### ISSUE TITLE
Arredondamento da imagem do perfil do usuário

### ISSUE THREAD

**Issue by halls2001** [JoseOda/TrabalhoGCS#20]
Acredito que ao deixarmos a foto de perfil arrendondada seguiremos a mesma ideia do próprio Github, mantendo assim a imagem em seu estilo original.  
![image](https://user-images.githubusercontent.com/85596702/175841081-0218edff-f9a0-4b85-8c42-3b6dc0155938.png)
![image](https://user-images.githubusercontent.com/85596702/175841120-6f3ea2ca-52e3-44f5-b15f-0f68771cf959.png)

**Comment by hugor1256** [comment]
Adorei @halls2001 tenho certeza que todos iremos preferir a interface arredondada

**Comment by joaovitormoitinho** [comment]
também gostei da ideia, acho um detalhe que deixa a aplicação bem mais bonita
