### ISSUE TITLE
Alinhar os dados com a imagem do usuário

### ISSUE THREAD

**Issue by halls2001** [JoseOda/TrabalhoGCS#24]
Deixar a interface mais amigável para o usuário deixando os dados alinhados abaixo da imagem.

![image](https://user-images.githubusercontent.com/85596702/175842243-4ea790e4-0e40-4cb4-b2c4-deaa5383e055.png)

**Comment by JoseOda** [comment]
Na verdade discordo um pouco sobre isso, já que os dados do usuário como nome e username fazem mais sentidos ficar ao lado da foto, enquanto os repositórios tudo embaixo

**Comment by GabrielCGon** [comment]
Seguindo a ideia do @JoseOda  seria bacana deixar centralizado a imagem.

**Comment by joaovitormoitinho** [comment]
eu também discordo um pouco do @halls2001, mais contudo eu acho que ficaria mais bonito aninhar esses dados com a parte de cima da imagem, e colocar os repositorios logo abaixo, o que acha @JoseOda ?

**Comment by joaovitormoitinho** [comment]
eu também discordo um pouco do @halls2001, mais contudo eu acho que ficaria mais bonito aninhar esses dados com a parte de cima da imagem, e colocar os repositorios logo abaixo, o que acha @enzookita  ?

**Comment by enzookita** [comment]
Eu concordo com você @joaovitormoitinho, é uma alteração interessante de se implementar. A estética do layout do nosso site é bem importante na minha opinião.

**Comment by enzookita** [comment]
Acabei de puxar as alterações feitas, pelo visto as modificações implementadas não estão responsivas. Segue uma imagem como evidência.

![image](https://user-images.githubusercontent.com/68976226/176067924-ab03402b-2bcc-43da-9fc8-8afe4361090c.png)

**Comment by halls2001** [comment]
Essa issue deverá ser reaberta, estou apresentando o mesmo problema

**Comment by joaovitormoitinho** [comment]
@enzookita a possível solução deste problema, pode ser no css, na class main-data, linha 95

**Comment by enzookita** [comment]
Certo, verifiquei e realizei uma alteração na margem do container. Segue o código:
`.main-data {
    display: flex;
    align-items: center;
    margin-bottom: 2em;
    width: 100%;
    margin-left: 10px;
    margin-right: 10px;
    justify-content: space-around;
}`

**Comment by enzookita** [comment]
Vou realizar a alteração na mesma branch em que foi feita a implementação dessa issue.

**Comment by enzookita** [comment]
@joaovitormoitinho, como você quebrou a porra do código deixou essa merda sem resposividade agr vc q arrume esse b.o

**Comment by enzookita** [comment]
@joaovitormoitinho, como você abriu a pull request dessa implementação, trate de arrumar esse erro urgentemente. O código para a alteração está no cometário acima.

**Comment by joaovitormoitinho** [comment]
ok, vou fazer essa alteração agora mesmo

**Comment by enzookita** [comment]
@halls2001, você aprovou a pull request #38, por favor tomar mais cuidado com as aprovações de pull resquests

**Comment by halls2001** [comment]
@enzookita  Ok irei me atentar nas proximas.
