### ISSUE TITLE
Alteração do fundo da tela

### ISSUE THREAD

**Issue by GabrielCGon** [JoseOda/TrabalhoGCS#26]
Estava revisando a issue #18  e como você esta na parte de alteração de modo seria interessante alterar o fundo da tela de cinza para branco.
![image](https://user-images.githubusercontent.com/48663139/175842657-fcae56bb-ef22-426a-81cf-a79239f510b2.png)

**Comment by enzookita** [comment]
Certo, vou estar mudando a cor do fundo da tela, apenas preciso saber da opnião de mais uma pessoa. @joaovitormoitinho o que você acha a respeito?

**Comment by joaovitormoitinho** [comment]
eu acho uma boa, pois acho que cinza é uma cor muito pouco usada, e pouco intuitiva para representar um modo light

**Comment by enzookita** [comment]
Certo, vou estar implementado então.

**Comment by enzookita** [comment]
Foi feita a implementação conforme a pull request #28

**Comment by joaovitormoitinho** [comment]
só o fundo branco eu achei que ficou meio vago, que tal acrescentar algum  detalhe, ou imagem. 
o que acham ?

**Comment by halls2001** [comment]
Discordo, como o nosso trabalho é bem simples e minimalista, caso adicionarmos um background extravagante perdermos a essência.
