### ISSUE TITLE
Aproximar o botão de submit da barra de pesquisar o usuário

### ISSUE THREAD

**Issue by halls2001** [JoseOda/TrabalhoGCS#3]
O botão de submit está muito distante da barra de pesquisa.
![image](https://user-images.githubusercontent.com/85596702/175790017-73c04292-15b3-4510-b34c-97159537f5e5.png)

**Comment by enzookita** [comment]
Realmente a margem do botão e da barra de pesquisa estão bem grandes, seria bom reduzir a distância entre eles

**Comment by joaovitormoitinho** [comment]
esse problema pode ter ocorrido por conta da variação do tamanho das telas

**Comment by JoseOda** [comment]
O erro provavelmente está no css, já que o margin top está com 30.5rem, normalmente é errado utilizar números tão altos numa rem

**Comment by enzookita** [comment]
Seria bom arrumar já esse problema, visto que @JoseOda já encontrou a solução

**Comment by enzookita** [comment]
Foi feito o merge com a branch principal, o layout foi corrigido
