### ISSUE TITLE
Mostrar os quatros primeiros repositórios do usuário.

### ISSUE THREAD

**Issue by joaovitormoitinho** [JoseOda/TrabalhoGCS#30]
A aplicação só está mostrando um repositório que o usuário possui. 
![image](https://user-images.githubusercontent.com/83321595/175844176-94de5231-fefe-4c12-a973-ed39a578bb02.png)

**Comment by halls2001** [comment]
Excelente ideia, e ao fixarmos o limite em quatro projetos evitamos que a aplicação fique poluida.

**Comment by JoseOda** [comment]
Já implementada essa issue!!!
