### ISSUE TITLE
Implementar o link para o repositório 

### ISSUE THREAD

**Issue by joaovitormoitinho** [JoseOda/TrabalhoGCS#31]
Ao clicar no repositório  do usuário pesquisado, ser direcionado para o repositório dele.

![image](https://user-images.githubusercontent.com/83321595/175844407-34d7919c-9de1-4c4e-b900-6711d7fcaeef.png)

**Comment by JoseOda** [comment]
Essa issue já foi reportada @joaovitormoitinho  por @enzookita, sendo ela a issue #17
