### ISSUE TITLE
Implementação de followers do usuário

### ISSUE THREAD

**Issue by enzookita** [JoseOda/TrabalhoGCS#32]
Estava verificando a API do Git e percebi que o nosso programa ficaria mais completo se mostrasse os seguidores do usuário.

**Comment by hugor1256** [comment]
Boa ideia, iria fazer essa implementação

**Comment by enzookita** [comment]
@halls2001, o que você acha dessa implementação?

**Comment by halls2001** [comment]
A ideia é boa, vamos implementar.

**Comment by joaovitormoitinho** [comment]
implementação concluida.
