### ISSUE TITLE
A barra de pesquisa está com um tamanho desproporcional

### ISSUE THREAD

**Issue by enzookita** [JoseOda/TrabalhoGCS#4]
Ao acessar o mecânismo de busca, verifiquei que a barra de pesquisa está com um tamanho fora do adequado. Conforme as evidências em anexo.

![image](https://user-images.githubusercontent.com/68976226/175790363-4087e2b5-462c-4ebf-9524-2758e8ef4573.png)

**Comment by joaovitormoitinho** [comment]
essa barra além de ter ficado feia, ficou muito desproporcional na tela, temos que resolver isso!

**Comment by halls2001** [comment]
Sim esse tamanho está equivocado, para solucionar basta colocar height: 2.5rem no arquivo styles.css que o problema será resolvido

**Comment by joaovitormoitinho** [comment]
pronto, o ralson conseguiu resolver o problema.

**Comment by hugor1256** [comment]
Muito bom, o novo modelo ficou bem melhor sendo mais amigável a utilização do usuário
