### ISSUE TITLE
Aumentar o tamanho do botão submit

### ISSUE THREAD

**Issue by joaovitormoitinho** [JoseOda/TrabalhoGCS#6]
o botão submit está pequeno, aumentar o tamanho do botão para ficar mais intuitivo e mais bonito para usuário. 

![image](https://user-images.githubusercontent.com/83321595/175790458-ead4c0fa-bbec-42e6-9592-2155d8cb3579.png)

**Comment by JoseOda** [comment]
Acredito que seria interessante aumentar o tamanho do botão, pra ficar mais intuitivo e com um design melhor

**Comment by enzookita** [comment]
Sim, o botão está realmente muito pequeno, aumentar o tamanho facilitaria e irá melhorar a experiência do usuário

**Comment by GabrielCGon** [comment]
Concordo com a mudança mas gostaria de ressaltar que é preciso tomar cuidado na hora de implementar o aumento, para que não fique grande demais.

**Comment by halls2001** [comment]
Concordo, esteticamente ele está em desacordo com os demais componentes da tela, diante disso, irei prosseguir com a implementação.
