### ISSUE TITLE
Mostrar o nome completo de uma pessoa quando o  perfil for encontrado

### ISSUE THREAD

**Issue by hugor1256** [JoseOda/TrabalhoGCS#8]
Fazer com que quando for feita uma pesquisa, mostrar o nome completo de uma pessoa quando o  perfil for encontrado

**Comment by enzookita** [comment]
Certo, vou verificar a API do GitHub para implementar essa nova função

**Comment by JoseOda** [comment]
Acho bem interessante, adicionarmos o nome completo do usuário, já que só aparecendo seu username fica um tanto quanto estranho

**Comment by hugor1256** [comment]
Acho que seria interessante ver outra funções que a API nos disponibiliza para mostrar a pesquisa com mais resultados .

**Comment by joaovitormoitinho** [comment]
é uma funcionalidade que pode ser muito útil, para os usuários dessa aplicação.

**Comment by JoseOda** [comment]
@enzookita conseguiu implementar essa nova funcionalidade com sucesso
